apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: {{ .Values.deployment.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
