name: Build and Deploy Flask App to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub using GitHub secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-hello-world:latest 


  deploy_to_k8s:
    runs-on: ubuntu-latest 
    needs: build_and_push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Start Minikube on local runner
    - name: Start Minikube
      run: |
        sudo minikube start --driver=none 

    # Configure kubectl to use Minikube
    - name: Set up kubectl
      uses: azure/setup-kubectl@v1

    - name: Set up Minikube kubectl context
      run: |
        echo "$(minikube kubeconfig)" > $HOME/.kube/config
    
    # Deploy Flask app to Kubernetes cluster
    - name: Deploy Flask app to Kubernetes
      run: kubectl apply -f flask_deployment.yaml
  
    # Deploy Flask service
    - name: Deploy Flask service to Kubernetes
      run: kubectl apply -f flask_service.yaml
